export const terrains = [
    'desert',
    'grasslands',
    'mountains',
    'jungle',
    'rainforests',
    'tundra',
    'ice caves',
    'mountain ranges',
    'swamp',
    'jungles',
    'gas giant',
    'forests',
    'lakes',
    'grassy hills',
    'swamps',
    'cityscape',
    'ocean',
    'rock',
    'mountain',
    'barren',
    'scrublands',
    'savanna',
    'canyons',
    'sinkholes',
    'volcanoes',
    'lava rivers',
    'caves',
    'rivers',
    'airless asteroid',
    'glaciers',
    'ice canyons',
    'fungus forests',
    'fields',
    'rock arches',
    'grass',
    'plains',
    'urban',
    'hills',
    'oceans',
    'bogs',
    'savannas',
    'rocky islands',
    'seas',
    'mesas',
    'unknown',
    'deserts',
    'reefs',
    'islands',
    'rocky deserts',
    'valleys',
    'ash',
    'toxic cloudsea',
    'plateaus',
    'verdant',
    'rocky canyons',
    'acid pools',
    'rocky',
    'vines',
    'cities',
    'savannahs',
    'cliffs',
];

export const climates = [
    'arid',
    'temperate',
    'tropical',
    'frozen',
    'murky',
    'windy',
    'hot',
    'artificial temperate',
    'frigid',
    'humid',
    'moist',
    'polluted',
    'unknown',
    'superheated',
    'subartic',
    'artic',
    'rocky',
];

export const residents = [
    'Luke Skywalker',
    'C-3PO',
    'Darth Vader',
    'Owen Lars',
    'Beru Whitesun lars',
    'R5-D4',
    'Biggs Darklighter',
    'Anakin Skywalker',
    'Shmi Skywalker',
    'Cliegg Lars',
    'Leia Organa',
    'Bail Prestor Organa',
    'Raymus Antilles',
    'Lobot',
    'Wicket Systri Warrick',
    'R2-D2',
    'Palpatine',
    'Padmé Amidala',
    'Jar Jar Binks',
    'Roos Tarpals',
    'Rugor Nass',
    'Ric Olié',
    'Quarsh Panaka',
    'Gregar Typho',
    'Cordé',
    'Dormé',
    'Finis Valorum',
    'Adi Gallia',
    'Jocasta Nu',
    'Boba Fett',
    'Lama Su',
    'Taun We',
    'Poggle the Lesser',
    'Tion Medon',
    'Chewbacca',
    'Tarfful',
    'Nute Gunray',
    'Obi-Wan Kenobi',
    'Wilhuff Tarkin',
    'Han Solo',
    'Wedge Antilles',
    'Greedo',
    'Jabba Desilijic Tiure',
    'Jek Tono Porkins',
    'Yoda',
    'IG-88',
    'Arvel Crynyd',
    'Qui-Gon Jinn',
    'R4-P17',
    'Bossk',
    'Lando Calrissian',
    'Ackbar',
    'Mon Mothma',
    'Nien Nunb',
    'Watto',
    'Sebulba',
    'Darth Maul',
    'Bib Fortuna',
    'Ayla Secura',
    'Ratts Tyerel',
    'Dud Bolt',
    'Gasgano',
    'Ben Quadinaros',
    'Mace Windu',
    'Ki-Adi-Mundi',
    'Kit Fisto',
    'Eeth Koth',
    'Saesee Tiin',
    'Yarael Poof',
    'Plo Koon',
    'Mas Amedda',
    'Luminara Unduli',
    'Barriss Offee',
    'Dooku',
    'Jango Fett',
    'Zam Wesell',
    'Dexter Jettster',
    'Wat Tambor',
    'San Hill',
    'Shaak Ti',
    'Grievous',
    'Sly Moore',
];
